# Generated by Django 3.2.9 on 2021-11-16 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=26)),
                ('confirm_password', models.CharField(max_length=26)),
                ('rank', models.CharField(choices=[('customer', 'customer'), ('seller', 'seller')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
