# Generated by Django 3.2.9 on 2021-11-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_detail',
            field=models.CharField(default='No name', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=10000, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(related_name='products', to='market.Tag'),
        ),
    ]
